README.md

Bux is amazing, congrats guys what a great tool.
Signed-off-by: Darren Kellenschwiler <d.kellenschwiler@nchain.com>

Quick typo fix in the README

---

src/index.test.ts
src/index.ts
src/interface.ts
src/transports/graphql.ts
src/transports/http.ts

⚠️ I left the TODO for the GraphQL function because it is not yet supported by Bux Server GraphQL

feat(BUX-184): add DeletePaymail function

---

.github/CODEOWNERS

fix(BUX-367): change order in codewners

---

src/bsv.d.ts
src/index.ts
src/interface.ts
src/utils/keys.ts

Description
-------------
- Added methods to generate random set of keys and  to get pub from xpriv

feat(BUX-190): add keys generation

---

README.md

BUX-432/Change Readme

---

src/index.ts
src/interface.ts
src/transports/http.ts

feat(BUX-498): remove BlockHeader methods

---

src/index.ts
src/transports/http.ts

BUX-476: Check UpdateXpubMetaData

---

package.json
src/transports/http.ts
yarn.lock

BUX-475: Show correct error message

---

src/index.ts

 BUX-483: Set admin key in constructor

---

src/transports/http.ts

BUX-479: Check new paymail

---

src/index.ts

- restore key generation methods

chore(BUX-542): restore key generation methods

---

src/index.test.ts
src/index.ts
src/interface.ts
src/transports/http.ts

BUX-527: Remove UnreserveUtxos

---

src/index.ts

The current implementation runs a check on the transaction during serialization after signing. Due to these checks, it's impossible to create an OP_RETURN output without satoshis assigned. Additionally, the implementation is not unified with the Bux client implementation in Golang.

fix(BUX-557): fix OP_RETURN tx issue

---

.github/workflows/release.yml

chore(000): use node v20 in workflows

---

package.json

chore: bump ver to 1.5.0

---

src/index.test.ts

Suggestion for refactoring of tests

refactor: use template literals tests instead of array for each

---

.github/workflows/test(ubuntu-latest).yml
package.json
yarn.lock

BUX-537: Run tests on PR

---

.github/mergify.yml

ci: quick cleanup of the mergify

---

package.json

feat(BUX-585): use official bsv scope of package; remove contributors from package.json

---

package.json

chore(BUX-585): start versions from 0.1.0

---

package.json
src/index.test.ts
src/transports/http.ts
yarn.lock

fix: back to global.fetch

---

package.json
src/transports/http.ts

fix: errors from http requests are not populated
